/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppThemesRouteImport } from './routes/_app.themes'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppBetsRouteImport } from './routes/_app.bets'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppThemesThemeIdRouteImport } from './routes/_app.themes.$themeId'
import { Route as AppBetsBetIdRouteImport } from './routes/_app.bets.$betId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppThemesRoute = AppThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppBetsRoute = AppBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppThemesThemeIdRoute = AppThemesThemeIdRouteImport.update({
  id: '/$themeId',
  path: '/$themeId',
  getParentRoute: () => AppThemesRoute,
} as any)
const AppBetsBetIdRoute = AppBetsBetIdRouteImport.update({
  id: '/$betId',
  path: '/$betId',
  getParentRoute: () => AppBetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/bets': typeof AppBetsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/feedback': typeof AppFeedbackRoute
  '/themes': typeof AppThemesRouteWithChildren
  '/bets/$betId': typeof AppBetsBetIdRoute
  '/themes/$themeId': typeof AppThemesThemeIdRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/bets': typeof AppBetsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/feedback': typeof AppFeedbackRoute
  '/themes': typeof AppThemesRouteWithChildren
  '/': typeof AppIndexRoute
  '/bets/$betId': typeof AppBetsBetIdRoute
  '/themes/$themeId': typeof AppThemesThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/bets': typeof AppBetsRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/themes': typeof AppThemesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/bets/$betId': typeof AppBetsBetIdRoute
  '/_app/themes/$themeId': typeof AppThemesThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/admin'
    | '/bets'
    | '/customers'
    | '/feedback'
    | '/themes'
    | '/bets/$betId'
    | '/themes/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/login'
    | '/admin'
    | '/bets'
    | '/customers'
    | '/feedback'
    | '/themes'
    | '/'
    | '/bets/$betId'
    | '/themes/$themeId'
  id:
    | '__root__'
    | '/_app'
    | '/access-denied'
    | '/login'
    | '/_app/admin'
    | '/_app/bets'
    | '/_app/customers'
    | '/_app/feedback'
    | '/_app/themes'
    | '/_app/'
    | '/_app/bets/$betId'
    | '/_app/themes/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/themes': {
      id: '/_app/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AppThemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bets': {
      id: '/_app/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof AppBetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/themes/$themeId': {
      id: '/_app/themes/$themeId'
      path: '/$themeId'
      fullPath: '/themes/$themeId'
      preLoaderRoute: typeof AppThemesThemeIdRouteImport
      parentRoute: typeof AppThemesRoute
    }
    '/_app/bets/$betId': {
      id: '/_app/bets/$betId'
      path: '/$betId'
      fullPath: '/bets/$betId'
      preLoaderRoute: typeof AppBetsBetIdRouteImport
      parentRoute: typeof AppBetsRoute
    }
  }
}

interface AppBetsRouteChildren {
  AppBetsBetIdRoute: typeof AppBetsBetIdRoute
}

const AppBetsRouteChildren: AppBetsRouteChildren = {
  AppBetsBetIdRoute: AppBetsBetIdRoute,
}

const AppBetsRouteWithChildren =
  AppBetsRoute._addFileChildren(AppBetsRouteChildren)

interface AppThemesRouteChildren {
  AppThemesThemeIdRoute: typeof AppThemesThemeIdRoute
}

const AppThemesRouteChildren: AppThemesRouteChildren = {
  AppThemesThemeIdRoute: AppThemesThemeIdRoute,
}

const AppThemesRouteWithChildren = AppThemesRoute._addFileChildren(
  AppThemesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBetsRoute: typeof AppBetsRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppThemesRoute: typeof AppThemesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBetsRoute: AppBetsRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppThemesRoute: AppThemesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
